language: python
python:
  - 3.7
before_install:
  - pip install poetry
install:
  - poetry install
script:
  - poetry run isort -c -rc git_commenter/
  - poetry run flake8 git_commenter/
  - poetry run pytest tests/
